# Generated by Django 4.1.7 on 2023-03-21 17:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.CreateModel(
            name='TransferReceipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=100)),
                ('bank_code', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2023, 3, 21, 17, 17, 4, 928216, tzinfo=datetime.timezone.utc), null=True)),
                ('trans_ref', models.CharField(blank=True, default='', max_length=100)),
                ('metadata', models.CharField(max_length=100)),
                ('ccy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
        ),
    ]
