# Generated by Django 4.1.7 on 2023-03-21 17:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_transaction_timestamp_transferreceipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferreceipient',
            name='ccy',
        ),
        migrations.AddField(
            model_name='transferreceipient',
            name='currency',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet'),
        ),
        migrations.AlterField(
            model_name='transferreceipient',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 21, 17, 24, 26, 372213, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
