# Generated by Django 4.1.7 on 2023-03-21 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_transferreceipient_ccy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferreceipient',
            name='currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='transferreceipient',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 21, 17, 26, 20, 269175, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
